name: Bug / Crash Report
description: Report a bug or crash
labels: [ "bug" ]
assignees:
    - aqariio
body:
    -   type: markdown
        attributes:
            value: |
                <br/>
                
                ### Hello! Thanks for taking the time to report an issue!
                
                If you meant to request a new feature or ask a question instead, please make a post on the **[Discussions](https://github.com/aqariio/Fowl-Play/discussions)** page!
                
                ### Before you create your bug / crash report:
                
                1. Use the search function to make sure your issue or crash hasn't already been reported
                2. Check if you are on the latest version of the mod
                
                --------------------------------------------------

    -   type: dropdown
        id: version
        attributes:
            label: "Version"
            options:
                - 1.21.1 - Fabric
                - 1.21.1 - NeoForge
                - 1.20.1 - Fabric
                - 1.20.1 - Forge
            default: 0
        validations:
            required: true

    -   type: markdown
        attributes:
            value: |
                <br/>
                
                **Add a description**
                
                - Clearly describe what the issue is and how to reproduce it (if possible)
                - Include the latest log if the issue causes a crash (usually found in \<instance>/logs/latest.log)
                - Screenshots and videos are very helpful!

    -   type: textarea
        id: description
        attributes:
            label: "Description"
            placeholder: "Describe your issue"
        validations:
            required: true